resources:

  # Monitoring module
  - ../vendor/katalog/monitoring/prometheus-operator
  - ../vendor/katalog/monitoring/prometheus-operated
  - ../vendor/katalog/monitoring/alertmanager-operated
  - ../vendor/katalog/monitoring/node-exporter
  - ../vendor/katalog/monitoring/kube-state-metrics
  - ../vendor/katalog/monitoring/grafana
  - ../vendor/katalog/monitoring/goldpinger
  - ../vendor/katalog/monitoring/configs

  # Logging module
  - ../vendor/katalog/logging/cerebro
  - ../vendor/katalog/logging/curator
  - ../vendor/katalog/logging/elasticsearch-single
  - ../vendor/katalog/logging/logging-operator
  - ../vendor/katalog/logging/logging-operated
  - ../vendor/katalog/logging/configs/kubernetes
  - ../vendor/katalog/logging/configs/ingress-nginx
  - ../vendor/katalog/logging/configs/audit
  - ../vendor/katalog/logging/configs/events
  - ../vendor/katalog/logging/kibana

  # Ingress module
  - ../vendor/katalog/ingress/nginx
  - ../vendor/katalog/ingress/forecastle

  # Ingress definitions
  - resources/ingress.yml

patchesStrategicMerge:

  - patches/alertmanager-operated-replicas.yml
  - patches/alertmanager-operated-resources.yml
  - patches/prometheus-operated-resources.yml
  - patches/prometheus-operator-resources.yml
  - patches/grafana-resources.yml
  - patches/kibana-resources.yml
  - patches/elasticsearch-resources.yml
  - patches/nginx-ingress-controller-resources.yml
